spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/soccer_league
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres1
  h2:
    console:
      enabled: false
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
